### ISSUE TITLE
energy storage is insanely high

### ISSUE THREAD

**Issue by VXsz** [Shadows-of-Fire/Hostile-Neural-Networks#20]
So I really like this mod and it looks awesome, and started to add it to my setup to check it out, when I reached the Simulation Chamber step to keep it training, the moment I put the machine it completely took over the energy grid and other machines barely get any power (I didn't realize it for a while why they stopped working), turns out it was trying to fill the 256M energy storage and taking every energy bit... can a limiter or something be implemented to help with this situation? cause to give you an example, my model went from %12 to around %21 using less than 1m RF, so all of that energy is probably not needed (at least in my use case for a cow model), I really wish the storage was something like 1m or at most 5m, I had to cut the Simulation Chamber off the grid manually and seems like the 15m that got charged are gonna last a long time with how slow it moves tbh

I love the mod aesthetics tho :D

**Comment by James103** [comment]
What modpack did you experience this issue on?

Do note some modpacks, including All the Mods 7, have configuration changes, one of which increases the Simulation Chamber battery capacity to 256 MFE instead of the default value of 2 MFE.

To resolve this, go into the config folder of the instance, open `hostilenetworks.cfg`, and reduce the value of `Sim Chamber Power Cap` to a more reasonable value.

The relevant line in the default config is:
```
    I:"Sim Chamber Power Cap"=2000000
```

**Comment by VXsz** [comment]
Oh yeah it's ATM 7, I thought it was the default of the mod's, sorry about that I will check the modpack's config files
