### ISSUE TITLE
Game crashes when right clicking.  All the Mods 8

### ISSUE THREAD

**Issue by RedactedIXI** [Shadows-of-Fire/Hostile-Neural-Networks#24]
https://mclo.gs/wwgfcbK

**Comment by javascriptin** [comment]
https://mclo.gs/EeSp74C

**Comment by javascriptin** [comment]
https://mclo.gs/EeSp74C

**Comment by Shadows-of-Fire** [comment]
This error would indicate that the blank data model item (referred to as a Model Framework in-game) wasn't registered.  Is it visible in JEI?  
This should be impossible, realistically.

**Comment by javascriptin** [comment]
For more context, this only occurred after updating my server to the latest All the Mods 8 version. It seems my modpack version initially did not have the mod installed within the existing world.

**Comment by javascriptin** [comment]
I can circle back with you if it is visible in JEI.

**Comment by javascriptin** [comment]
I confirmed that the Model Framework is not visible in JEI. This issue seems very niche so far, I can only assume that it originated either from a user error during the update process, or there is some sort of rare conflict that doesn't sit well from pre-existing worlds to the post-existing world (hard to say when this issue occurred through a mod pack). 

You're the expert, let me know if there is anything I can do to help gather more clues regarding this issue.

**Comment by Shadows-of-Fire** [comment]
You would then need to verify that the mod is actually present on both the client and the server.

It being present on the client but not server might be able to create the behavior you're seeing

**Comment by javascriptin** [comment]
Issue resolved, took your advice and dug into the server files myself using FileZilla. Makes me wonder if the ATM-8 server pack is up-to-date with their client-side download.

**Comment by Shadows-of-Fire** [comment]
You may want to report that to them.
