### ISSUE TITLE
Data Models stopped existing

### ISSUE THREAD

**Issue by coldbru7** [Shadows-of-Fire/Hostile-Neural-Networks#31]
I have a modded server running ATM8 after updating to 4.1.0 some of the data models stopped existing, and when i attempt to get them in game by the usual method I get the prompt "created x model successfully" but the Data Model is broken, and shows unknown.

**Comment by LordCorellon** [comment]
I had this same issue, The root cause appears to be a kubejs script, I'm not sure which one but the issue disappeared after I deleted the kubejs folder off the server and replaced it fresh from the ATM zip file.

I may have used the client one, I'm not sure but the issue is definetely with one of the scripts and replacing them fixed it for my server.  Also BTW the same scripts work if you run the world local or over LAN so it's an issue with either the server scripts or the scripts and the server jar/libraries
