### ISSUE TITLE
Data model bugged

### ISSUE THREAD

**Issue by 17enn** [Shadows-of-Fire/Hostile-Neural-Networks#32]
I used a framework on a shulker and put it into the deep learner and i'm getting this error where the text is bugged and doesn't work.  This is happening to like half the mobs in the modpack I am playing on All the mods 8 on the latest version had this issue for a few days now
![image](https://github.com/Shadows-of-Fire/Hostile-Neural-Networks/assets/104277455/a77ec720-84c8-4cf9-8a33-08aed2c15fdf)
![image](https://github.com/Shadows-of-Fire/Hostile-Neural-Networks/assets/104277455/c3698b14-c5a7-4783-b172-8a6f1d620bfd)
The screenshots are of shulker and mimic data models

**Comment by LordCorellon** [comment]
I had this same issue, The root cause appears to be a kubejs script, I'm not sure which one but the issue disappeared after I deleted the kubejs folder off the server and replaced it fresh from the ATM zip file.

I may have used the client one, I'm not sure but the issue is definetely with one of the scripts and replacing them fixed it for my server.  Also BTW the same scripts work if you run the world local or over LAN so it's an issue with either the server scripts or the scripts and the server jar/libraries
